# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10

  - name: Projects
    url: project
    weight: 20

  - name: Talks
    url: talk
    weight: 30

  - name: Courses
    url: course
    weight: 40
    identifier: courses
  # - name: Undergraduate Courses
  #   PageRef: course/undergraduate-courses/_index.md
  #   weight: 10
  #   parent: courses
  # - name: Graduate Courses
  #   PageRef: course/graduate-courses/_index.md
  #   weight: 20
  #   parent: courses

  - name: Publications
    url: publication
    weight: 50
  
  - name: Members
    url: people
    weight: 60
  
  
  
